# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calc.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 318)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(20, 10, 361, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAutoFillBackground(True)
        self.label.setIndent(-1)
        self.label.setObjectName("label")
        self.pushButton_equal = QtWidgets.QPushButton(Form)
        self.pushButton_equal.setGeometry(QtCore.QRect(331, 250, 61, 41))
        self.pushButton_equal.setStyleSheet("background-color: rgb(255, 170, 0);\n"
"")
        self.pushButton_equal.setObjectName("pushButton_equal")
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setGeometry(QtCore.QRect(171, 190, 61, 41))
        self.pushButton_3.setStyleSheet("background-color: rgb(81, 81, 81);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 16pt \"MS Shell Dlg 2\";")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_minus = QtWidgets.QPushButton(Form)
        self.pushButton_minus.setGeometry(QtCore.QRect(332, 190, 61, 41))
        self.pushButton_minus.setStyleSheet("background-color: rgb(255, 170, 0);")
        self.pushButton_minus.setObjectName("pushButton_minus")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(90, 190, 61, 41))
        self.pushButton_2.setStyleSheet("background-color: rgb(81, 81, 81);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 16pt \"MS Shell Dlg 2\";")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_1 = QtWidgets.QPushButton(Form)
        self.pushButton_1.setGeometry(QtCore.QRect(10, 190, 61, 41))
        self.pushButton_1.setStyleSheet("background-color: rgb(81, 81, 81);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 16pt \"MS Shell Dlg 2\";")
        self.pushButton_1.setObjectName("pushButton_1")
        self.pushButton_add = QtWidgets.QPushButton(Form)
        self.pushButton_add.setGeometry(QtCore.QRect(251, 190, 61, 41))
        self.pushButton_add.setStyleSheet("background-color: rgb(255, 170, 0);\n"
"")
        self.pushButton_add.setObjectName("pushButton_add")
        self.pushButton_9 = QtWidgets.QPushButton(Form)
        self.pushButton_9.setGeometry(QtCore.QRect(172, 70, 61, 41))
        self.pushButton_9.setStyleSheet("background-color: rgb(81, 81, 81);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 16pt \"MS Shell Dlg 2\";")
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_del = QtWidgets.QPushButton(Form)
        self.pushButton_del.setGeometry(QtCore.QRect(252, 70, 61, 41))
        self.pushButton_del.setStyleSheet("background-color: rgb(62, 125, 188);")
        self.pushButton_del.setObjectName("pushButton_del")
        self.pushButton_6 = QtWidgets.QPushButton(Form)
        self.pushButton_6.setGeometry(QtCore.QRect(171, 130, 61, 41))
        self.pushButton_6.setStyleSheet("background-color: rgb(81, 81, 81);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 16pt \"MS Shell Dlg 2\";")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_div = QtWidgets.QPushButton(Form)
        self.pushButton_div.setGeometry(QtCore.QRect(332, 130, 61, 41))
        self.pushButton_div.setStyleSheet("background-color: rgb(255, 170, 0);")
        self.pushButton_div.setObjectName("pushButton_div")
        self.pushButton_5 = QtWidgets.QPushButton(Form)
        self.pushButton_5.setGeometry(QtCore.QRect(90, 130, 61, 41))
        self.pushButton_5.setStyleSheet("background-color: rgb(81, 81, 81);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 16pt \"MS Shell Dlg 2\";")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_7 = QtWidgets.QPushButton(Form)
        self.pushButton_7.setGeometry(QtCore.QRect(11, 70, 61, 41))
        self.pushButton_7.setStyleSheet("background-color: rgb(81, 81, 81);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 16pt \"MS Shell Dlg 2\";\n"
"")
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_4 = QtWidgets.QPushButton(Form)
        self.pushButton_4.setGeometry(QtCore.QRect(10, 130, 61, 41))
        self.pushButton_4.setStyleSheet("background-color: rgb(81, 81, 81);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 16pt \"MS Shell Dlg 2\";")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_AC = QtWidgets.QPushButton(Form)
        self.pushButton_AC.setGeometry(QtCore.QRect(333, 70, 61, 41))
        self.pushButton_AC.setStyleSheet("background-color: rgb(255, 64, 0);")
        self.pushButton_AC.setObjectName("pushButton_AC")
        self.pushButton_8 = QtWidgets.QPushButton(Form)
        self.pushButton_8.setGeometry(QtCore.QRect(91, 70, 61, 41))
        self.pushButton_8.setStyleSheet("background-color: rgb(81, 81, 81);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 16pt \"MS Shell Dlg 2\";")
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_mul = QtWidgets.QPushButton(Form)
        self.pushButton_mul.setGeometry(QtCore.QRect(251, 130, 61, 41))
        self.pushButton_mul.setStyleSheet("background-color: rgb(255, 170, 0);")
        self.pushButton_mul.setObjectName("pushButton_mul")
        self.pushButton_power = QtWidgets.QPushButton(Form)
        self.pushButton_power.setGeometry(QtCore.QRect(170, 250, 61, 41))
        self.pushButton_power.setStyleSheet("background-color: rgb(255, 170, 0);")
        self.pushButton_power.setObjectName("pushButton_power")
        self.pushButton_0 = QtWidgets.QPushButton(Form)
        self.pushButton_0.setGeometry(QtCore.QRect(9, 250, 61, 41))
        self.pushButton_0.setStyleSheet("background-color: rgb(81, 81, 81);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 16pt \"MS Shell Dlg 2\";")
        self.pushButton_0.setObjectName("pushButton_0")
        self.pushButton_point = QtWidgets.QPushButton(Form)
        self.pushButton_point.setGeometry(QtCore.QRect(89, 250, 61, 41))
        self.pushButton_point.setStyleSheet("background-color: rgb(81, 81, 81);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 16pt \"MS Shell Dlg 2\";")
        self.pushButton_point.setObjectName("pushButton_point")
        self.pushButton_mod = QtWidgets.QPushButton(Form)
        self.pushButton_mod.setGeometry(QtCore.QRect(250, 250, 61, 41))
        self.pushButton_mod.setStyleSheet("background-color: rgb(255, 170, 0);")
        self.pushButton_mod.setObjectName("pushButton_mod")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(250, 300, 131, 16))
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Calculator"))
        self.label.setText(_translate("Form", "0"))
        self.pushButton_equal.setText(_translate("Form", "="))
        self.pushButton_3.setText(_translate("Form", "3"))
        self.pushButton_minus.setText(_translate("Form", "-"))
        self.pushButton_2.setText(_translate("Form", "2"))
        self.pushButton_1.setText(_translate("Form", "1"))
        self.pushButton_add.setText(_translate("Form", "+"))
        self.pushButton_9.setText(_translate("Form", "9"))
        self.pushButton_del.setText(_translate("Form", "DEL"))
        self.pushButton_6.setText(_translate("Form", "6"))
        self.pushButton_div.setText(_translate("Form", "/"))
        self.pushButton_5.setText(_translate("Form", "5"))
        self.pushButton_7.setText(_translate("Form", "7"))
        self.pushButton_4.setText(_translate("Form", "4"))
        self.pushButton_AC.setText(_translate("Form", "AC"))
        self.pushButton_8.setText(_translate("Form", "8"))
        self.pushButton_mul.setText(_translate("Form", "X"))
        self.pushButton_power.setText(_translate("Form", "^"))
        self.pushButton_0.setText(_translate("Form", "0"))
        self.pushButton_point.setText(_translate("Form", "."))
        self.pushButton_mod.setText(_translate("Form", "%"))
        self.label_2.setText(_translate("Form", "Developed by: Shreesha KJ"))


if __name__ == "__main_calc__":
	pass